apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdf-gen-canary
  namespace: default
spec:
  image: "repo.adeo.no:5443/integrasjon/pdf-gen:@@VERSION@@"
  port: 8080
  team: integrasjon
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 70
  healthcheck:
    liveness:
      path: /is_alive
      timeout: 5
      initialDelay: 5
      periodSeconds: 5
      failureThreshold: 30
    readiness:
      path: /is_alive
      timeout: 5
      initialDelay: 5
      periodSeconds: 5
      failureThreshold: 30
  leaderElection: false
  prometheus:
    enabled: true
    path: /prometheus
  istio:
    enabled: false
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses: []
